version: '3'

services:

    php:
        container_name: fl_php
        build:
            context: ./php
            dockerfile: Dockerfile-php-fpm
        env_file:
            - .env
        volumes:
            - ./php/config/php.ini:/usr/local/etc/php/php.ini:rw
            - ../:/script:ro

    nginx:
        container_name: fl_nginx
        image: nginx
        ports:
            - 8080:80
            - 443:443
        volumes:
            - ../:/app:ro
            - ./nginx/log:/var/log/nginx
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:rw
            # - ./nginx/config/test/:/etc/nginx/conf.d
    #         - ./nginx/certbot/conf:/etc/letsencrypt
    #         - ./nginx/certbot/www:/var/www/certbot
    # certbot:
    #     image: certbot/certbot
    #     volumes:
    #         - ./nginx/certbot/conf:/etc/letsencrypt
    #         - ./nginx/certbot/www:/var/www/certbot

    mysql:
        container_name: fl_mysql
        image: mysql:5.7
        ports:
            - ${DB_PORT}:3306
        env_file:
            - ../.env
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf


    phpmyadmin:
        container_name: fl_phpmyadmin
        env_file:
            - ./.env
        image: phpmyadmin/phpmyadmin
        ports:
            - 8082:80
        links:
            - mysql:db

    maildev:
        container_name: fl_mail
        image: djfarrelly/maildev
        ports:
            - ${MAILDEV_PORT}:80
